[Feat] 매칭 상태에 따른 matchingDoneCount 계산 및 게시글 상태 업데이트 기능 구현
JNU-econovation/BuddyBridge_BE pull request #182
Opened 2024-10-13 06:14 UTC by injae-348

## PR 유형

- [X] 새로운 기능 추가
- [ ] 버그 수정
- [X] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 기타 (아래에 상세 내용 기입)

## 변경 사항 요약

매칭 상태에 따라 게시글 상태 업데이트
매칭 상태 변경 시 headcount와 matchingDoneCount를 비교해 상태 업데이트 수행
매칭이 headcount만큼 완료된 경우 발생하는 비즈니스 예외 처리(에러 코드 추가)

## 관련 이슈

close #180 

## 체크리스트

- [X] 코드가 제대로 작동하는지 확인
- [X] 테스트가 추가되었거나 기존 테스트가 통과하는지 확인
- [X] 관련 문서(ERD, API 문서 등)가 업데이트되었는지 확인

2024-10-13 11:14 UTC, Profile-exe requested changes
수고하셨습니다! 코멘트 확인 부탁드려요

2024-10-13 11:14 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/exception/MatchingErrorCode.java
> +    EXCEEDED_MATCHING_LIMIT("MA003", HttpStatus.BAD_REQUEST, "모집이 완료되었습니다.")
모집 완료인데, "매칭 제한을 초과"했다는 열거형 식별자가 들어있네요. 이름을 수정해보는건 어떠신가요?

2024-10-13 11:14 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/repository/MatchingRepository.java
> +    Integer countMatchingDoneByPostId(Long post_id);
네이티브 쿼리 옵션을 `ture`로 둔 이유가 있나요?

2024-10-13 11:14 UTC, Profile-exe commented on src/main/java/econo/buddybridge/post/entity/Post.java
> +    private Integer matchingDoneCount;
`matchingRepository`에서 카운트 쿼리를 두었는데, 왜 여기서 필드로 갖고 있는건가요?

2024-10-13 12:01 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/exception/MatchingErrorCode.java
> +    EXCEEDED_MATCHING_LIMIT("MA003", HttpStatus.BAD_REQUEST, "모집이 완료되었습니다.")
모집이 완료되었으니깐 MATCHING_COMPLETED 이런식으로 바꿔볼게요

2024-10-13 12:07 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/repository/MatchingRepository.java
> +    Integer countMatchingDoneByPostId(Long post_id);
이 부분은 네이티브 쿼리를 사용하는 블로그를 보고 따라했습니다.. 
이유보다는 작성하고 돌아가네 하면서 넘어갔었습니다..
native Query에 대해서 조금 찾아보니 단순 집계 보다는 복잡한 쿼리 작성 시 사용한다고 하네요.
또한 DB가 바뀔 때 해당 SQL 문이 아닌 경우 동작을 못하는 문제도 발생한다고 합니다.
검색하면서 찾게 된 JPA의 JPQL을 사용하는 방식으로 변경해보고자 합니다.

2024-10-13 12:10 UTC, injae-348 commented on src/main/java/econo/buddybridge/post/entity/Post.java
> +    private Integer matchingDoneCount;
다시 살펴보니 해당 부분도 제거 하는 게 좋은 거 같습니다.
PostResDto에서 만들어둔 집계 함수를 사용하면 될 거 같아요.
다시 생각해볼 수 있는 코멘트였습니다. 감사합니다!

2024-10-15 11:09 UTC, Profile-exe approved these changes
수고하셨습니다!

2024-10-15 11:25 UTC, merged