[REFACTOR] 정책 변경에 따른 게시글 내용 수정
JNU-econovation/BuddyBridge_BE pull request #224
Opened 2024-11-28 09:01 UTC by injae-348

## PR 유형

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [X] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [X] 코드 리팩토링
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 기타 (아래에 상세 내용 기입)

## 변경 사항 요약

#### 정책 변경으로 더 이상 사용 안 하는 필드 제거 및 Request, Response DTO 필드 수정
 - 게시글에 대한 Request(생성, 업데이트) 및 Response(조회) DTO에서 headcount 필드 제거
 - 메인 페이지 게시글 Response DTO 추가
 - AssistanceType으로 "기타" 항목 추가
 - 제목, 내용, 댓글, 채팅 글자 수 제한(사용자 입력)
 - Response DTO matchingDoneCount필드 제거

## 참고 사항
#### About `headCount` and `matchingDoneCount`
응답 및 요청 필드에서는 `headCount`와 `matchingDoneCount`를 전부 제거했습니다.
다만, `Post` Entity필드인 `headCount`와 `MatchingRepository`의 `countMatchingDoneByPostId()`는 그대로 두었습니다.
FE 측에서 바라보자면 `headCount`와 `matchingDoneCount`를 응답과 요청에 대한 DTO에서 제거함으로써 불필요한 정보를 받지 않을 수 있습니다.
BE 측에서는 headCount를 1인 default 값으로 주고, matchingDoneCount를 내부적으로 사용하여 게시글 상태를 업데이트 시킬 때는 반드시 매칭 상태 변경이 선행되어야 함을 확인할 수 있다고 생각했습니다. 이전 방식처럼 매칭의 상태를 업데이트 시킬 때 게시글의 상태가 바로 변경되게 해도 좋지만, N명 모집에 적용한 코드를 사용하고 싶은 욕심도 들었습니다.

명덕님 의견은 어떤가요?

## 관련 이슈

close #222 

## 체크리스트

- [X] 코드가 제대로 작동하는지 확인
- [X] 테스트가 추가되었거나 기존 테스트가 통과하는지 확인
- [X] 관련 문서(ERD, API 문서 등)가 업데이트되었는지 확인

2024-11-29 14:11 UTC, Profile-exe requested changes
수고하셨습니다! 코멘트 확인해주세요!
추가로 리펙토링도 함께 수행해주시면 감사하겠습니다. 아래 코드를 보시면
```java
    // 게시글 작성 회원과 현재 로그인한 회원 일치 여부 판단
    private void validatePostAuthor(Post post, Long memberId) {
        if ((post.getPostType() == PostType.GIVER && !post.getAuthor().getId().equals(memberId)) ||
                (post.getPostType() == PostType.TAKER && !post.getAuthor().getId().equals(memberId))) {
            throw PostUnauthorizedAccessException.EXCEPTION;
        }
    }
```
게시글 작성자와 현재 회원의 일치 여부를 판단하는데, 불필요한 조건이 있는 것 같습니다.
그리고 `memberId` 말고 엔티티를 가져와서 `getAuthor()`랑 비교하는게 적절할 것 같은데, 어떻게 생각하시나요?

2024-11-29 14:11 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
>          }
매칭 완료된 게시물은 모집완료(`FINISHED`)인데, `existsMatchingDone` 대신 이를 활용해도 좋겠네요!

2024-11-29 14:11 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +        saveFirstChatMessage(matching, taker);
메서드로 분리한거 아주 좋네요 👍

2024-11-29 14:11 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +        if (existsMatchingDone(post)) {
여기서도 게시글 상태가 모집 완료(`FINISHED`)라면 이미 완료된 매칭이 존재하는 거니 이를 활용해도 좋을 것 같아요

2024-11-29 14:11 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +    }
게시글 상태가 매칭 완료 여부에 전적으로 의존한다면, 게시글 엔티티에는 상태를 두지 않는 것은 어떨까요?

2024-11-29 14:28 UTC, injae-348 commented
> 수고하셨습니다! 코멘트 확인해주세요! 추가로 리펙토링도 함께 수행해주시면 감사하겠습니다. 아래 코드를 보시면
> 
> ```java
>     // 게시글 작성 회원과 현재 로그인한 회원 일치 여부 판단
>     private void validatePostAuthor(Post post, Long memberId) {
>         if ((post.getPostType() == PostType.GIVER && !post.getAuthor().getId().equals(memberId)) ||
>                 (post.getPostType() == PostType.TAKER && !post.getAuthor().getId().equals(memberId))) {
>             throw PostUnauthorizedAccessException.EXCEPTION;
>         }
>     }
> ```
> 
> 게시글 작성자와 현재 회원의 일치 여부를 판단하는데, 불필요한 조건이 있는 것 같습니다. 그리고 `memberId` 말고 엔티티를 가져와서 `getAuthor()`랑 비교하는게 적절할 것 같은데, 어떻게 생각하시나요?

지금 보니 왜 저렇게 짠지 모르겠는 조건이 포함되어 있네요. 저 부분 수정하고 함수 명에 맞게 Member Object끼리 비교하는게 좋은 것 같습니다.

2024-11-29 14:38 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +    }
"게시글 상태가 매칭 완료 여부에 전적으로 의존한다" 저도 했던 말인데 코드로 옮겨오면서 멋대로 해석했네요. '게시글과 매칭을 각각 Entity로 선언해줬으니 분리 시켜야지' 했던 것 같네요. 어떻게 처리할지 감이 잡혀 재 수정 해보겠습니다..!

2024-11-29 14:39 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +        if (existsMatchingDone(post)) {
밑에 있는 로직 수정하면서 existsMatchingDone을 쓰던 부분도 수정해볼게요.

2024-11-29 14:57 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
>          }
게시글에서 상태 필드를 제거하면서 `existsMatchingDone()`은 유지하는 방향으로 가져가볼게요!

2024-11-29 14:58 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +        if (existsMatchingDone(post)) {
여기서도 동일하게 사용할게요!

2024-12-01 07:40 UTC, Profile-exe requested changes

2024-12-01 07:40 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +        validatePostAuthor(matching.getPost(), loginMember);
위에서는 `author`로 변경된 것 같은데, 여기는 `loginMember`인 이유가 있나요?

2024-12-01 07:40 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +        if (!post.getAuthor().equals(author)) {
매개변수명 아주 좋습니다 👍

2024-12-01 07:52 UTC, Profile-exe approved these changes
수고하셨습니다!

2024-12-01 07:53 UTC, merged