[FEAT] 마이페이지 매칭완료된 게시글 목록 조회 및 매칭 상태 업데이트
JNU-econovation/BuddyBridge_BE pull request #240
Opened 2024-12-31 15:05 UTC by injae-348

## PR 유형

- [X] 새로운 기능 추가
- [X] 버그 수정
- [X] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [X] 코드 리팩토링
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [X] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 기타 (아래에 상세 내용 기입)

## 변경 사항 요약

`matchingStatus`가 DONE, VOLUNTEERING_COMPLETED, VOLUNTEERING_VERIFIED인 게시글 목록 마이페이지에서 조회 기능 추가

유한상태머신 형식으로 매칭 상태 업데이트

## 관련 이슈

close #239 

## 체크리스트

- [X] 코드가 제대로 작동하는지 확인
- [X] 테스트가 추가되었거나 기존 테스트가 통과하는지 확인
- [X] 관련 문서(ERD, API 문서 등)가 업데이트되었는지 확인

2025-01-02 08:19 UTC, Profile-exe requested changes
수고하셨습니다! 코멘트 확인 부탁드려요.
`MatchingState`와 `MatchingStatus` 서로 많이 헷갈릴 것 같은데, 한 상태만 두는 방식은 불가능한가요?

2025-01-02 08:19 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +    }
데이터베이스에서 쿼리로 확인하는 방법은 어떤가요?

2025-01-02 08:19 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/repository/MatchingRepository.java
> +    );
`JPQL`을 사용하는데, 엔티티 대신 `id` 필드를 넘기는 이유가 있나요?

2025-01-02 08:19 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/exception/MatchingErrorCode.java
> +    DUPLICATE_MATCHING("MA005", HttpStatus.BAD_REQUEST, "이미 생성된 매칭이 존재합니다."),
문구에 맞게 `MATCHING_ALREADY_EXISTS`는 어떤가요?

2025-01-02 08:19 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +        }
`Id`까지 가지 않고 `Post`까지만 꺼내서 비교할 수 있지 않을까요? 쿼리를 짤 때나 비교를 할 때 엔티티에서 `Id`를 꺼내 비교하거나 파라미터로 넘겨주는 이유가 궁금합니다! 성능 향상 등 이점이 있는 것인가요?

큰 차이가 없으면 엔티티까지만 비교하거나 파라미터로 넘겨 가독성을 좋게 할 수 있을 것 같아서요!

2025-01-02 08:19 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +    }
`MatchingUpdateDto`를 사용하는 유일한 곳이 `MatchingStatusEvent`를 가져오는 것이라면 호출 시점에서 파라미터로 넘기는건 어떤가요?

2025-01-02 08:19 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/entity/Matching.java
> +
`import` 정렬이 된 것인가요?

2025-01-02 08:19 UTC, Profile-exe commented on src/main/java/econo/buddybridge/post/service/PostService.java
> +        List<CompletedVolunteerPostDto> content = PostMapper.getCompletedVolunteerPostDtos(matchings);
`getMatchingsByMemberRoleAndStatus`에서 `CompletedVolunteerPostDto`를 바로 반환하지 않고 `PostMapper#getCompletedVolunteerPostDtos`를 사용하는 이유가 궁금합니다!

`@Projection`을 사용하면 바로 DTO로 가져올 수 있고, `stream()`으로 순회하며 `DTO`로 변환하는 오버헤드가 사라질 것 같아서요.

2025-01-03 08:58 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/repository/MatchingRepository.java
> +    );
`JPQL`을 검색해보니 Entity 객체를 대상으로 쿼리 한다는 특징을 가지고 있네요. 굳이 Id가 아닌 `giver`와 `firstMember`가 같은지 비교하는게 좋은 것 같아요. 수정해볼게요

2025-01-03 08:59 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/exception/MatchingErrorCode.java
> +    DUPLICATE_MATCHING("MA005", HttpStatus.BAD_REQUEST, "이미 생성된 매칭이 존재합니다."),
동의합니다

2025-01-03 09:00 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/entity/Matching.java
> +
저장 시 자동으로 정렬 설정을 해줬는데, 설정이 서로 다른지 확인해보면 좋을 것 같아요.

2025-01-03 13:02 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +    }
계층 레이어에 대한 발표를 들었을 때, 해당 로직은 비즈니스적인 로직 보다는 데이터베이스에서 처리하는게 옳은 것 같네요.

2025-01-03 13:07 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +    }
확인해보니 매칭을 업데이트 시킬 때만 사용하고 있으며, 업데이트 시킬 때 Event만 가져오기 때문에 Dto로 감싸지 않고 파라미터로 넘겨 불필요한 래퍼클래스를 제거 할 수 있을거 같아요.

2025-01-03 13:20 UTC, injae-348 commented on src/main/java/econo/buddybridge/post/service/PostService.java
> +        List<CompletedVolunteerPostDto> content = PostMapper.getCompletedVolunteerPostDtos(matchings);
정확히 기억이 나지 않는데 이때 이유가 있어 따로 분리 했었던 것 같아요.
다시 보니 Repository에서 한 번에 게시글 리스트를 생성 가능할 거 같아. 수정해보도록 하겠습니다.

2025-01-03 13:58 UTC, injae-348 commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +        }
제가 생각했을 때는 각각의 게시글은 고유한 Id를 가지고 있기에 Id끼리 비교하는게 직관적이라 생각했습니다.

`Id`의 비교와 `Entity`의 비교를 찾아보니 `Post`끼리 비교할 경우 주소가 같은지 만 검사하기에 속도 적인 측면에서 훨 빠릅니다. 다만, 서로 다른 영속성 컨텍스트에서 비교 작업을 수행하는 경우 각각의 `Entity`가 다를 가능성이 있어 Id로 비교하는게 안정적이라 합니다.

해당 리뷰 부분은 하나의 Transactional 안에서 실행되고 있으며, 하나의 영속성 컨텍스트 내에서 비교 작업이 일어나기에 post 끼리 비교하는게 효율적인거 같습니다.

2025-01-03 14:19 UTC, injae-348 commented
> 수고하셨습니다! 코멘트 확인 부탁드려요. `MatchingState`와 `MatchingStatus` 서로 많이 헷갈릴 것 같은데, 한 상태만 두는 방식은 불가능한가요?

> Buddy J : 기존에 `MatchingStatus`가 있으면서도 `MatchingState`를 추가해 헷갈릴 수 있다고 생각합니다. `Status`만 두어 할 수도 있지만, 제가 State를 도입하게 된 이유는 매칭에 대한 순수한 상태를 나타내는 Status와 상태 전이를 처리하는 State로 분리하고자 했습니다. 상태 전이 로직을 분리함으로써 `Matching`의 책임을 줄일 수 있고,  코드가 나눠져 관리하기 쉽다고 생각했습니다. 

State와 Status 두 용어 모두 한국어로 "상태"이기에 헷갈릴 여지가 있다 봅니다.  아래 블로그에서 그 차이점을 읽어보니 받아들이기 쉬웠습니다. 명덕님 의견은 어떠실까요?
https://velog.io/@curiosity806/%EA%B0%9C%EB%B0%9C-%EC%83%81%EC%8B%9D-status-vs-state

2025-01-03 14:31 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/repository/MatchingRepository.java
> +    );
`Query Method`를 사용한다면 `id`를 사용하는 상황이 생길 수 있어요. 현재 제가 구현중인 다중 삭제에서는 `In` 쿼리를 이용해 `id` 컬렉션을 넘깁니다.

```java
List<Post> findByIdIn(List<Long> postIds);
```

하지만, "**Entity로 작성이 가능한 쿼리 메소드나 JPQL**"의 경우에는 `id` 대신 `Entity` 사용이 가능하다면 `Entity`로 작성해야 코드도 간결해지고 쉽게 읽힐 것 같습니다!

2025-01-03 14:32 UTC, Profile-exe commented on src/main/java/econo/buddybridge/matching/service/MatchingService.java
> +        }
오 주소 검사로 인한 이점도 있군요! 하나 배워갑니다 👍

2025-01-03 14:41 UTC, Profile-exe commented
> 기존에 `MatchingStatus`가 있으면서도 `MatchingState`를 추가해 헷갈릴 수 있다고 생각합니다. `Status`만 두어 할 수도 있지만, 제가 State를 도입하게 된 이유는 매칭에 대한 순수한 상태를 나타내는 Status와 상태 전이를 처리하는 State로 분리하고자 했습니다. 상태 전이 로직을 분리함으로써 `Matching`의 책임을 줄일 수 있고, 코드가 나눠져 관리하기 쉽다고 생각했습니다.
> 
> State와 Status 두 용어 모두 한국어로 "상태"이기에 헷갈릴 여지가 있다 봅니다. 아래 블로그에서 그 차이점을 읽어보니 받아들이기 쉬웠습니다. 명덕님 의견은 어떠실까요? https://velog.io/@curiosity806/%EA%B0%9C%EB%B0%9C-%EC%83%81%EC%8B%9D-status-vs-state

"매칭의 상황"을 나타내는 `Status`, "매칭의 특정 시점의 상태"를 나타내는 `State`로 구분할 수 있다는 것은 알겠습니다. 이대로 구현해도 큰 문제는 없지만 앞으로 개발을 해나가면서 이 용어 정의를 잘 인지하고 개발할 수 있을지 조금 걱정이 되네요.

`recruit` 프로젝트의 `com.econovation.recruitdomain.domains.applicant.domain.state` 패키지를 보면  `MongoAnswer`의 필드인 `ApplicantState`가 `PassState`를 갖고있습니다. 그리고 `PassState`열거형이 각 상태를 가지며 비즈니스 규칙에 따라 상태 전이 여부를 결정합니다.

 그래서 이 프로젝트에서도 상태를 하나로 통합해 구현하면 좋을 것 같다는 생각을 해보았습니다. 우선 개발 진행을 위해 구현 자체는 여기서 크게 바꾸지 않고 남은 피드백들만 반영해보는게 좋을 것 같습니다!

2025-01-04 10:09 UTC, Profile-exe approved these changes
projection 적용하니 코드가 깔끔해졌네요 수고하셨습니다!

2025-01-04 10:48 UTC, merged